all:
	@coregen -r -p coregen.cgp -b blk_mem64k.xco

clean:
	@rm -f  *.cgc       
	@rm -f  *.ngc       
	@rm -f  *.mif       
	@rm -f  *.v       
	@rm -f  *.edn       
	@rm -f  *.gise
	@rm -f  *.ise
	@rm -f  *.veo
	@rm -f  *.xise
	@rm -f  *.xncf
	@rm -f  *.asy
	@rm -f  *.txt
	@rm -f  *.tcl  
	@rm -f  *.pdf  
	@rm -f  *.log  
	@rm -rf tmp
